name: 'Lerna Audit'
description: 'GitHub Action to run NPM audit on Lerna monorepo'
inputs:
  include-root:
    description: 'Run audit at root level of project'
    required: false
    default: 'true'
  npm-audit-args:
    description: 'Args that will be passed to "npm audit"'
    required: false
    default: ''
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
